# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface1(object):
    def setupUi(self, interface1):
        interface1.setObjectName("interface1")
        interface1.resize(350, 460)
        interface1.setMinimumSize(QtCore.QSize(350, 460))
        interface1.setMaximumSize(QtCore.QSize(350, 460))
        interface1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(interface1)
        self.centralwidget.setObjectName("centralwidget")
        self.pic1 = QtWidgets.QFrame(self.centralwidget)
        self.pic1.setGeometry(QtCore.QRect(70, 50, 221, 221))
        self.pic1.setStyleSheet("image: url(:/images/1.png);")
        self.pic1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pic1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pic1.setObjectName("pic1")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, 270, 321, 61))
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.by = QtWidgets.QLabel(self.centralwidget)
        self.by.setGeometry(QtCore.QRect(30, 440, 281, 20))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.by.setFont(font)
        self.by.setObjectName("by")
        self.loadingprogress = QtWidgets.QLabel(self.centralwidget)
        self.loadingprogress.setGeometry(QtCore.QRect(10, 380, 331, 21))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.loadingprogress.setFont(font)
        self.loadingprogress.setAlignment(QtCore.Qt.AlignCenter)
        self.loadingprogress.setObjectName("loadingprogress")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(70, 350, 201, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(0, 240, 240);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    color: rgb(0,0, 0);\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        interface1.setCentralWidget(self.centralwidget)

        self.retranslateUi(interface1)
        QtCore.QMetaObject.connectSlotsByName(interface1)

    def retranslateUi(self, interface1):
        _translate = QtCore.QCoreApplication.translate
        interface1.setWindowTitle(_translate("interface1", "Projet Géodésie"))
        self.title.setText(_translate("interface1", "<html><head/><body><p><span style=\" font-size:28pt; color:#4444a5;\">Projet de Géodésie</span></p></body></html>"))
        self.by.setText(_translate("interface1", "<html><head/><body><p><span style=\" font-size:7pt;\">Designed By : MEJDOUB Abdelkader &amp; MOGNI Hamza</span></p></body></html>"))
        self.loadingprogress.setText(_translate("interface1", "Please wait..."))
import bg_rc
